apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-rancher
  namespace: default
data:
  terraform.tfvars: |+
    control_plane_count    = "1"
    worker_count           = "2"
    vm_name                = "rancher"
    vm_template_name       = "bionic-server-cloudimg-amd64"
    vm_cpu                 = 2
    vm_ram                 = 4096
    vsphere_vcenter        = "sfps-vcsa.rtp.openenglab.netapp.com"
    vsphere_user           = ""
    vsphere_password       = ""
    vsphere_unverified_ssl = "true"
    vsphere_datacenter     = "RTP SFPS Lab"
    vsphere_resource_pool  = "RancherHCI"
    vm_datastore           = "sfps-lab-esx-ds01"
    vm_network             = "Lab-VMNet1-VL20"
    vm_domain              = "example.local.net"
    vsphere_vm_folder      = "JohnG/testing-jw"
    rancher_server_url     = "my.rancher.org"
    ssh_private_key        = "~/.ssh/id_rsa"
    ssh_public_key         = "~/.ssh/id_rsa.pub"
    deliverables_path      = "/deliverables"